const CART_KEY='obli_shop_cart_v4';
const DISCORD_URL='https://discord.gg/JrmV5Gub35';
let cart=[];
try{cart=JSON.parse(localStorage.getItem(CART_KEY)||'[]')}catch(e){cart=[]}
const money=n=>Number(n||0).toLocaleString('fr-FR',{minimumFractionDigits:2,maximumFractionDigits:2})+' €';
function saveCart(){localStorage.setItem(CART_KEY,JSON.stringify(cart));renderCart()}
function ensureCartUI(){
 if(document.getElementById('cartDrawer'))return;
 document.body.insertAdjacentHTML('beforeend',`<div class="cart-backdrop" id="cartBackdrop"></div><aside class="cart-drawer" id="cartDrawer" aria-hidden="true"><div class="cart-head"><h2>🛒 Mon panier</h2><div><button class="cart-clear" id="cartClear">🗑 Vider</button><button class="cart-close" id="cartClose" aria-label="Fermer">×</button></div></div><div class="cart-items" id="cartItems"></div><div class="cart-checkout" id="cartCheckout"><div class="discord-login-box"><span>Discord requis pour commander</span><button id="discordLogin">Se connecter avec Discord</button></div><div class="promo"><input placeholder="Code promo" disabled><button disabled>Appliquer</button></div><div class="cart-total"><strong>Total</strong><b id="cartTotal">0,00 €</b></div><button class="checkout-btn" id="checkoutBtn">VALIDER LA COMMANDE →</button><small class="checkout-note">La création automatique du ticket Discord sera activée après configuration du bot sécurisé.</small></div></aside>`);
 document.getElementById('cartClose').onclick=closeCart;document.getElementById('cartBackdrop').onclick=closeCart;document.getElementById('cartClear').onclick=()=>{cart=[];saveCart()};document.getElementById('discordLogin').onclick=()=>alert('Connexion Discord bientôt disponible. Nous allons la relier à une application Discord sécurisée.');document.getElementById('checkoutBtn').onclick=()=>{if(!cart.length)return;alert('Étape suivante : connecter Discord et le bot de tickets. Pour le moment, tu vas être redirigé vers le Discord OBLI SHOP.');window.open(DISCORD_URL,'_blank')};
}
function renderCart(){ensureCartUI();const box=document.getElementById('cartItems'),checkout=document.getElementById('cartCheckout');document.querySelectorAll('.cart-count').forEach(x=>x.textContent=cart.reduce((s,i)=>s+(i.qty||1),0));if(!cart.length){box.innerHTML='<div class="cart-empty">Ton panier est vide</div>';checkout.classList.add('hidden');return}checkout.classList.remove('hidden');box.innerHTML=cart.map((i,n)=>`<div class="cart-line"><div class="cart-thumb">${i.icon||'📦'}</div><div class="cart-info"><strong>${i.name}</strong><span>${money(i.price)}</span><small>Quantité : ${i.qty||1}</small></div><button class="remove-item" data-index="${n}">🗑</button></div>`).join('');box.querySelectorAll('.remove-item').forEach(b=>b.onclick=()=>{cart.splice(+b.dataset.index,1);saveCart()});document.getElementById('cartTotal').textContent=money(cart.reduce((s,i)=>s+(Number(i.price)||0)*(i.qty||1),0))}
function openCart(e){if(e)e.preventDefault();ensureCartUI();document.getElementById('cartDrawer').classList.add('open');document.getElementById('cartBackdrop').classList.add('open');document.body.classList.add('cart-open');renderCart()}
function closeCart(){document.getElementById('cartDrawer')?.classList.remove('open');document.getElementById('cartBackdrop')?.classList.remove('open');document.body.classList.remove('cart-open')}
window.addToCart=(name,price,icon='📦')=>{const found=cart.find(x=>x.name===name);if(found)found.qty=(found.qty||1)+1;else cart.push({name,price:Number(price),qty:1,icon});saveCart();openCart()};
document.querySelectorAll('.cart').forEach(a=>{a.removeAttribute('href');a.innerHTML='🛒 <span class="cart-count">0</span>';a.setAttribute('role','button');a.onclick=openCart});
document.querySelectorAll('nav a').forEach(a=>a.addEventListener('click',()=>{document.querySelectorAll('nav a').forEach(x=>x.classList.remove('active'));a.classList.add('active')}));
ensureCartUI();renderCart();
